# Generated by Django 4.2.21 on 2025-06-01 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactReguest',
            new_name='ContactRequest',
        ),
    ]
