# Generated by Django 4.2.21 on 2025-06-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_contactreguest_contactrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blogpost',
            new_name='book',
        ),
    ]
