# Generated by Django 4.2.21 on 2025-06-02 14:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_rename_blogpost_comment_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='blogpost',
            new_name='book',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'book')},
        ),
    ]
