# Generated by Django 4.2.21 on 2025-06-13 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_starrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starrating',
            name='value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
