# Generated by Django 4.2.21 on 2025-06-13 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_alter_starrating_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='starrating',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='starrating',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_ratings', to='blog.blogpost'),
        ),
        migrations.AlterUniqueTogether(
            name='starrating',
            unique_together={('book', 'user')},
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
