# Generated by Django 4.2.21 on 2025-06-14 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_starrating_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='starrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
